IGI/LR5/Lab5/carshowroom/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.views.generic import RedirectView

from catalog.views import RegisterView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
]

urlpatterns += [
    path('catalog/', include('catalog.urls')),
    path('sign-up', RegisterView.as_view(), name='sign-up'),
]
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]

# Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

IGI/LR5/Lab5/catalog/urls.py
from django.urls import path
from . import views
from django.urls import re_path as url

from .views import OrderedProductsByUserListView, AllClientsForEmployeeView, client_list, EmployeeListView, \
    ReviewListView, ReviewCreateView, ClientsGroupedByCityView, LogoutView, privacy, about

urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^profile/$', views.profile_view, name='profile'),
    url(r'^products/$', views.ProductListView.as_view(), name='products'),
    url(r'^product/(?P<pk>\d+)$', views.ProductDetailView.as_view(), name='product-detail'),
    url(r'^manufacturers/$', views.ManufacturerListView.as_view(), name='manufacturers'),
    url(r'^manufacturer/(?P<pk>\d+)$', views.ManufacturerDetailView.as_view(), name='manufacturer-detail'),
    url(r'^faq/$', views.faq, name='faq'),
    # path('books/', views.BookListView.as_view(), name='books'),
]

urlpatterns += [
    url(r'^my-orders/$', views.OrdersByUserListView.as_view(), name='my-orders'),
]

urlpatterns += [
    url(r'^all-orders/$', views.AllOrdersForEmployeeView.as_view(), name='all-orders'),
]

urlpatterns += [
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('order/<uuid:order_id>/', OrderedProductsByUserListView.as_view(), name='order-detail'),
]
urlpatterns += [
    url(r'^order/(?P<pk>[-\w]+)/change-status/$', views.change_status_employee, name='change-status-employee'),
]

urlpatterns += [url(r'^cart/$', views.CartView.as_view(), name='cart'),
                ]
urlpatterns += [url('create-order/', views.create_order, name='create-order'),
                url(r'^increase-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.increase_quantity,
                    name='increase-quantity'),
                url(r'^decrease-quantity/(?P<product_instance_id>[0-9a-f-]+)/$', views.decrease_quantity,
                    name='decrease-quantity'),
                url(r'^remove-from-cart/(?P<product_instance_id>[0-9a-f-]+)/$', views.remove_from_cart,
                    name='remove-from-cart'),
                url(r'^privacy/$', privacy, name='privacy'),
                url(r'^news/$', views.news, name='news'),
                url(r'^news/(?P<article_id>\d+)/$', views.article_detail, name='article_detail'),
                url(r'^about/$', about, name='about'),
                path('onlineshop/cart/apply-promo-code/', views.apply_promo_code, name='apply-promo-code'),
                path('promo-codes/', views.PromoCodeListView.as_view(), name='promo-codes'),
                path('clients/all/', views.AllClientsForEmployeeView.as_view(), name='all-clients'),
                path('clients/', views.client_list, name='clients'),
                path('contacts/', EmployeeListView.as_view(), name='contacts'),
                path('reviews/', ReviewListView.as_view(), name='reviews'),
                path('reviews/add/', ReviewCreateView.as_view(), name='add-review'),
                path('clients_grouped_by_city/', ClientsGroupedByCityView.as_view(), name='clients_grouped_by_city'),
                url(r'^jobs/$', views.jobs, name='jobs'),
                ]

urlpatterns += [
    path('logout/', LogoutView.as_view(), name='logout'),
]

IGI/LR5/Lab5/catalog/models.py
from datetime import datetime
from django.db import models
from django.db.models.signals import m2m_changed
from django.dispatch import receiver
from django.urls import reverse
from django.contrib.auth.models import User, Group
import uuid


class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    photo = models.ImageField(upload_to='', null=True, blank=True)
    job_description = models.TextField(default='No description')
    phone = models.CharField(max_length=20, null=True)
    email = models.EmailField(default='default@gmail.com')

    def __str__(self):
        return f"{self.user.username}"

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group, created = Group.objects.get_or_create(name='Employees')
        self.user.groups.add(group)


class Review(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField()
    text = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        stars = '*' * self.rating
        return f'{self.user}: {stars} {self.text}'

    def get_rating(self):
        return '*' * self.rating


class ProductType(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    product_type = models.ForeignKey(ProductType, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='products/', null=True)
    manufacturer = models.ForeignKey('Manufacturer', on_delete=models.SET_NULL, null=True)

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('product-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class Article(models.Model):
    title = models.CharField(max_length=200)
    summary = models.CharField(max_length=200)
    image = models.ImageField(upload_to='articles/')
    content = models.TextField(max_length=10000)
    publication_date = models.DateTimeField(default=datetime.now())

    def __str__(self):
        return self.title


class Client(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    phone_number = models.CharField(max_length=20, default='', blank=True)
    city = models.CharField(max_length=100, default='Minsk')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        group = Group.objects.get(name='Salon clients')
        self.user.groups.add(group)

    class Meta:
        ordering = ["first_name", "last_name"]

    def __str__(self):
        return f"{self.user.username}"


class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    order = models.ForeignKey('Order', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.product.name} x {self.quantity}"


class ProductInstance(models.Model):
    """
    Model representing a specific copy of a book (i.e. that can be borrowed from the library).
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular product across whole shop")
    product = models.ForeignKey('Product', on_delete=models.SET_NULL, null=True)
    # order = models.ForeignKey(Order, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    customer = models.ForeignKey(Client, on_delete=models.SET_NULL, null=True, blank=True)

    class Meta:
        permissions = (("can_mark_issued", "Set product as issued"),)

    def __str__(self):
        """
        String for representing the Model object
        """
        return '%s (%s)' % (self.id, self.product.name)

    @property
    def total_price(self):
        return self.product.price * self.quantity


class PromoCode(models.Model):
    code = models.CharField(max_length=10)
    discount = models.DecimalField(max_digits=10, decimal_places=2)

    # expiration_date = models.DateField(default=datetime.date(datetime.now()))

    def __str__(self):
        return self.code


class Order(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular order across whole shop")
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    order_date = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.00, editable=False)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ('p', 'Processing'),
        ('s', 'Shipped'),
        ('d', 'Delivered'),
        ('i', 'Issued'),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default='p', help_text='Order status')

    def save(self, *args, **kwargs):
        self.total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            self.total_price *= (1 - self.promo_code.discount / 100)
        super().save(*args, **kwargs)

    def calculate_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()

    def __str__(self):
        return f"Order {self.id} by {self.client}"


# @receiver(m2m_changed, sender=Order.products.through)
# def update_total_price(sender, instance, action, **kwargs):
#     if action == "post_add" or action == "post_remove":
#         instance.total_price = instance.calculate_total_price()
#         instance.save()


class Cart(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    products = models.ManyToManyField(ProductInstance)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    promo_code = models.ForeignKey(PromoCode, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"Cart for {self.client}"

    def update_total_price(self):
        total_price = sum(
            product_instance.product.price * product_instance.quantity for product_instance in self.products.all())
        if self.promo_code:
            total_price *= (1 - self.promo_code.discount / 100)
        self.total_price = total_price
        self.save()


class Manufacturer(models.Model):
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()

    def get_absolute_url(self):
        """
        Returns the url to access a particular book instance.
        """
        return reverse('manufacturer-detail', args=[str(self.id)])

    def __str__(self):
        return self.name


class CompanyInfo(models.Model):
    text = models.TextField()
    video = models.URLField(blank=True, null=True)
    logo = models.ImageField(upload_to='logos/', blank=True, null=True)
    history = models.TextField(blank=True, null=True)
    details = models.TextField(blank=True, null=True)


class FAQ(models.Model):
    question = models.TextField()
    answer = models.TextField()
    date_added = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.question


class Job(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

IGI/LR5/Lab5/catalog/forms.py
from django.core.validators import RegexValidator
from .models import Order, Review
from datetime import date
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class OrderStatusForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['status']


class RegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)
    date_of_birth = forms.DateField(
        help_text="Required. Format: YYYY-MM-DD",
        input_formats=['%Y-%m-%d'],
        widget=forms.DateInput(format='%Y-%m-%d', attrs={'type': 'date', 'max': date.today().strftime('%Y-%m-%d')})
    )
    phone_number = forms.CharField(
        validators=[
            RegexValidator(
                regex=r'^\+375 \((29|33|44|25)\) \d{3}-\d{2}-\d{2}$',
                message="Phone number must be entered in the format: '+375 (29) XXX-XX-XX'. Up to 15 digits allowed."
            )
        ]
    )

    CITIES = [
        ('Minsk', 'Minsk'),
        ('Brest', 'Brest'),
        ('Gomel', 'Gomel'),
        ('Grodno', 'Grodno'),
        ('Mogilev', 'Mogilev'),
        ('Vitebsk', 'Vitebsk'),
    ]
    city = forms.ChoiceField(choices=CITIES, required=True)

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ["username", "email", "password1", "password2", "date_of_birth", "phone_number"]

    def clean_date_of_birth(self):
        dob = self.cleaned_data.get('date_of_birth')
        today = date.today()
        if (dob.year + 18, dob.month, dob.day) > (today.year, today.month, today.day):
            raise forms.ValidationError('You must be at least 18 years old to register.')

        return dob


class ReviewForm(forms.ModelForm):
    RATING_CHOICES = [(i, str(i)) for i in range(1, 6)]  # Choices from 1 to 5

    rating = forms.ChoiceField(choices=RATING_CHOICES, widget=forms.Select(), required=True)

    class Meta:
        model = Review
        fields = ['rating', 'text']


from django.test import TestCase
from .forms import RegisterForm
from datetime import date, timedelta

class RegisterFormTest(TestCase):
    def test_register_form_valid(self):
        form = RegisterForm(data={
            'username': 'testuser',
            'email': 'testuser@example.com',
            'password1': 'testpassword123',
            'password2': 'testpassword123',
            'date_of_birth': (date.today() - timedelta(days=365*20)).strftime('%Y-%m-%d'),  # 20 years old
            'phone_number': '+375 (29) 123-45-67',
            'city': 'Minsk'
        })
        self.assertTrue(form.is_valid())

    def test_register_form_invalid(self):
        form = RegisterForm(data={
            'username': 'testuser',
            'email': 'testuser@example.com',
            'password1': 'testpassword123',
            'password2': 'testpassword123',
            'date_of_birth': date.today().strftime('%Y-%m-%d'),  # Today's date, i.e., less than 18 years old
            'phone_number': '+375 (29) 123-45-67',
            'city': 'Minsk'
        })
        self.assertFalse(form.is_valid())

IGI/LR5/Lab5/catalog/templates/catalog/article_detail.html
{% extends "base_generic.html" %} 
 
{% block content %} 
    <h1>{{ article.title }}</h1> 
    <img src="{{ article.image.url }}" alt="{{ article.title }}" style="max-width:300px; max-height:300px;"> 
    <p>{{ article.content }}</p>

    <a href="{%  url 'news' %}">Back to all news</a>
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/change_status_employee.html
{% extends "base_generic.html" %}
{% block content %}

<h1>Change Order Status</h1>

    <form method="POST" >
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Change Status</button>
    </form>

    <h2>Order Details</h2>
    <ul>
    {% for product in order.products.all %}
        <li>{{ product.product.name }} (Quantity: {{ product.quantity }})</li>
    {% endfor %}
    </ul>

    <a href="{% url 'all-orders' %}">Back to All Orders</a>

{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/client_list_for_employee.html
{% extends "base_generic.html" %} 
 
{% block content %} 
  <h1>Client List</h1> 
 
  <form method="GET" action="{% url 'clients' %}">
    <input type="text" name="search" placeholder="Search clients" value="{{ request.GET.search }}"> 
    <input type="submit" value="Search"> 
  </form> 
 
  <table> 
    <thead> 
      <tr> 
        <th>Username</th> 
        <th>Email</th> 
        <th>Date Joined</th> 
      </tr> 
    </thead> 
    <tbody> 
    {% for client in object_list %} 
      <tr> 
        <td>{{ client.user.username }}</td> 
        <td>{{ client.user.email }}</td> 
        <td>{{ client.user.date_joined }}</td> 
      </tr> 
    {% empty %} 
      <tr> 
        <td colspan="3">No clients found.</td> 
      </tr> 
    {% endfor %} 
    </tbody> 
  </table> 
 
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/company_info.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>О компании</h1>
    <img src="{{ info.logo.url }}" alt="Company Logo" height=200px width=200px>
    <p>{{ info.text }}</p>
    <video width="320" height="240" controls>
        <source src="{{ info.video.url}}" type="video/mp4">
    </video>
    <h2>История</h2>
    <p>{{ info.history }}</p>
    <h2>Реквизиты</h2>
    <p>{{ info.details }}</p>
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/employee_list.html
{% extends "base_generic.html" %} 
 
{% block content %} 
  <h1>Contacts</h1> 
 
  {% for employee in object_list %} 
    <div> 
      {% if employee.photo %} 
        <img src="{{ employee.photo.url }}" alt="{{ employee.first_name }} {{ employee.last_name }}" width="200"> 
      {% endif %} 
      <h2>{{ employee.first_name }} {{ employee.last_name }}</h2> 
      <p>{{ employee.position }}</p> 
      {% if employee.job_description %} 
        <p>{{ employee.job_description }}</p> 
      {% endif %} 
      {% if employee.phone %} 
        <p>Phone: {{ employee.phone }}</p> 
      {% endif %} 
      {% if employee.email %} 
        <p>Email: <a href="mailto:{{ employee.email }}">{{ employee.email }}</a></p> 
      {% endif %} 
    </div> 
  {% empty %} 
    <p>No employees found.</p> 
  {% endfor %} 
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/jobs.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Jobs</h1>
    {% for job in jobs %}
        <div>
            <h2>{{ job.title }}</h2>
            <p>{{ job.description }}</p>
        </div>
    {% empty %}
        <p>There are no jobs</p>
    {% endfor %}
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/manufacturer_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ manufacturer.name }}</h1>

  <p><strong>Email:</strong> {{ manufacturer.email}}</p>


  <div style="margin-left:20px;margin-top:20px">
    <h4>Products</h4>

    {% for product in manufacturer.product_set.all %}
    <hr>
    <p><strong>Name:</strong> <a href="{{ product.get_absolute_url }}">{{ product.name }}</a></p>
    <p><strong>Price:</strong> {{ product.price }}</p>
    {% endfor %}
  </div>
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/manufacturer_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Manufacturer List</h1>

    {% if manufacturer_list %}
    <ul>

      {% for manufacturer in manufacturer_list %}
      <li>
        <a href="{{ manufacturer.get_absolute_url }}">{{ manufacturer.name }}</a> ({{manufacturer.phone}})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>There are no manufacturers.</p>
    {% endif %}
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/news.html
{% extends "base_generic.html" %} 

{% block content %}
    <h1>News</h1>

    {% if articles %}
        {% for article in articles %}
            <div>
                <h2>{{ article.title }}</h2>
                <p>{{ article.summary }}</p>
                <img src="{{ article.image.url }}" alt="{{ article.title }}" style="max-width:300px; max-height:300px;">
                <a href="{% url 'article_detail' article.id %}">Read more</a>
            </div>
        {% endfor %}
    {% else %}
        <p>No articles available.</p>
    {% endif %}
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/order_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Order: </h1>

  <p><strong>Date:</strong> {{ order.order_date }}</p>
  <p><strong>Total Price:</strong> {{ order.total_price }}</p>
  <p><strong>Status:</strong> {{ order.get_status_display }}</p>
    <p><strong>Promocode: </strong>{{ order.promo_code }}</p>

  <h2>Products:</h2>
  {% if order.products.all %}
    <ul>
      {% for product_instance in order.products.all %}
        <li>
          <p><strong>Name:</strong> {{ product_instance.product.name }}</p>
          <p><strong>Price:</strong> {{ product_instance.product.price }}</p>
          <p><strong>Quantity:</strong> {{ product_instance.quantity }}</p>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No products in this order.</p>
  {% endif %}
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/privacy.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Privacy Policy</h1>

<p>My site's privacy policy.</p>

{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/product_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Name: {{ product.name }}</h1>
    {% if  product.photo %}
           <img src="{{ product.photo.url }}" alt="{{ product.name }}" width="200">
          {% endif %}
  <p><strong>Description:</strong> {{ product.description }}</p>
  <p><strong>Price:</strong> {{ product.price }}</p>
  <p><strong>Product type:</strong> {{ product.product_type }}</p>
  <p><strong>Unit of measure:</strong> {{ product.unit_of_measure }}</p>
  <p><strong>Manufacturer:</strong> <a href="{% url 'manufacturer-detail' product.manufacturer.id %}">{{ product.manufacturer }}</a></p>
  {% if user.is_authenticated and user.client %}
  <form method="POST" action="{% url 'add_to_cart' product.id %}">
    {% csrf_token %}
    <input type="submit" value="Add to cart">
  </form>
  {% endif %}
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/reviews.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Reviews</h1>

  {% for review in object_list %}
    <div>
      <h2>{{ review.user.username }}</h2>
    <p>{{ review.get_rating }}</p>
      <p>{{ review.text }}</p>
      <p>Date: {{ review.date }}</p>
    </div>
  {% empty %}
    <p>No reviews found.</p>
  {% endfor %}

  {% if user.is_authenticated %}
    <a href="{% url 'add-review' %}">Add a review</a>
  {% else %}
    <a href="{% url 'login' %}">Log in to add a review</a>
  {% endif %}
{% endblock %}

IGI/LR5/Lab5/catalog/templates/catalog/user_cart.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Your Cart</h1>

    {% if cart.products.all %}
    <ul>
      {% for product_instance in cart.products.all %}
      <li>
            <a href="{% url 'product-detail' product_instance.product.id %}">{{ product_instance.product.name }}</a> (Quantity: {{ product_instance.quantity }}, Price: {{ product_instance.product.price }}, Total: <span id="total-price-{{ product_instance.id }}">{{ product_instance.total_price }}</span>)
            <div style="display: flex;">
                <form action="{% url 'increase-quantity' product_instance.id %}" method="post" class="quantity-form" data-product-instance-id="{{ product_instance.id }}">
                    {% csrf_token %}
                    <input type="submit" value="+">
                </form>
                <form action="{% url 'decrease-quantity' product_instance.id %}" method="post" class="quantity-form" data-product-instance-id="{{ product_instance.id }}">
                    {% csrf_token %}
                    <input type="submit" value="-">
                </form>
                <form action="{% url 'remove-from-cart' product_instance.id %}" method="post">
                    {% csrf_token %}
                    <input type="submit" value="Удалить из корзины">
                </form>
            </div>
      </li>
      {% endfor %}
    </ul>
         <!-- Promo code form -->
    <form action="{% url 'apply-promo-code' %}" method="post">
        {% csrf_token %}
        <input type="text" name="promo_code" placeholder="Enter promo code">
        <input type="submit" value="Apply promo Code">
    </form>

    <p>Total price: {{ cart.total_price }}</p>
    <form action="{% url 'create-order' %}" method="post">
        {% csrf_token %}
        <input type="submit" value="Create order">
    </form>
    {% else %}
        <p>Your cart is empty.</p>
    {% endif %}
{% endblock %}